from __future__ import annotations
import argparse
from pathlib import Path
import pandas as pd

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PACKAGE_ROOT / "data" / "internal"
OUTPUT_DIR = PACKAGE_ROOT / "outputs" / "internal"
AUDIT_DIR = PACKAGE_ROOT / "audit"

def main() -> int:
    ap = argparse.ArgumentParser(description="Train or retain recovered ridge logistic internal model outputs.")
    ap.add_argument("--force-train", action="store_true", help="Fit ridge logistic models from matrices and CV splits.")
    args = ap.parse_args()
    pred_out = OUTPUT_DIR / "internal_prediction_scores.csv"
    coef_out = OUTPUT_DIR / "internal_model_coefficients.csv"
    if not args.force_train:
        if pred_out.exists() and coef_out.exists():
            print("Recovered outputs retained. Use --force-train to regenerate from matrices.")
            return 0
        raise SystemExit("Recovered outputs absent; use --force-train with original matrices.")
    try:
        from sklearn.linear_model import LogisticRegression
        from sklearn.preprocessing import StandardScaler
    except Exception as exc:
        raise SystemExit(f"scikit-learn required for --force-train: {exc}")
    matrices = {
        "microbiome": pd.read_csv(DATA_DIR / "hmp2_microbiome_processed_matrix.csv").set_index("sample_id"),
        "metabolome": pd.read_csv(DATA_DIR / "hmp2_metabolome_processed_matrix.csv").set_index("sample_id"),
    }
    splits = pd.read_csv(DATA_DIR / "internal_cv_splits.csv")
    pos = pd.read_csv(AUDIT_DIR / "positive_class_definition.csv").set_index("task")
    rows, coefs = [], []
    for modality, mat in matrices.items():
        features = list(mat.columns)
        include_col = f"included_in_{modality}_model"
        for (task, fold), sdf in splits.groupby(["task", "fold"]):
            sdf = sdf[sdf[include_col].astype(bool)]
            train_ids = [s for s in sdf.loc[sdf.split.eq("train"), "sample_id"] if s in mat.index]
            test_ids = [s for s in sdf.loc[sdf.split.eq("test"), "sample_id"] if s in mat.index]
            if not train_ids or not test_ids:
                continue
            y_train = sdf.set_index("sample_id").loc[train_ids, "binary_label"].astype(int)
            scaler = StandardScaler()
            x_train = scaler.fit_transform(mat.loc[train_ids, features].astype(float))
            x_test = scaler.transform(mat.loc[test_ids, features].astype(float))
            model = LogisticRegression(penalty="l2", solver="liblinear", class_weight="balanced", max_iter=2000, random_state=20260609)
            model.fit(x_train, y_train)
            prob = model.predict_proba(x_test)[:, 1]
            smap = sdf.set_index("sample_id")
            for sid, p in zip(test_ids, prob):
                rows.append({"task": task, "fold": fold, "modality": modality, "sample_id": sid, "subject_id": smap.loc[sid, "subject_id"], "true_label": int(smap.loc[sid, "binary_label"]), "positive_class": pos.loc[task, "positive_class"], "negative_class": pos.loc[task, "negative_class"], "prediction_score": float(p), "prediction_probability": float(p), "split": "test", "model_type": "ridge_logistic_regression_l2_rerun", "scaler_fit_on": "training_fold_only", "notes": "Generated by --force-train."})
            for feat, coef in zip(features, model.coef_[0]):
                coefs.append({"task": task, "fold": fold, "modality": modality, "feature_id": feat, "feature_name": feat, "coefficient": float(coef), "intercept": float(model.intercept_[0]), "model_type": "ridge_logistic_regression_l2_rerun", "source_matrix": f"hmp2_{modality}_processed_matrix.csv", "notes": "Generated by --force-train."})
    pd.DataFrame(rows).to_csv(pred_out, index=False)
    pd.DataFrame(coefs).to_csv(coef_out, index=False)
    print("07_train_internal_models complete")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
